pipeline:
  name: 构建七牛云节点定义docker镜像
  ref: jianmu_runner_qiniu_image_builder
  description: 构建七牛云节点定义docker镜像
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-runners/jianmu-runner-qiniu.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
  image_build:
    type: docker_image_build:1.0.0
    param:
      workspace: ${git_clone.git_path}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      docker_file: Dockerfile
      image_name: jianmudev/jianmu-runner-qiniu
      image_tag: ${node_build.version}
      docker_build_path: .