pipeline:
  name: 构建七牛云节点定义docker镜像
  ref: jianmu_runner_qiniu_image_builder
  description: 构建七牛云节点定义docker镜像
  git_clone:
    type: git:v1.0
    param:
      workspace: jianmu-runner-qiniu
      remote_url: https://gitee.com/jianmu-runners/jianmu-runner-qiniu.git
      commit_branch: master
  node_build:
    type: node_build:14.16.1-alpine3.13
    param:
      workspace: jianmu-runner-qiniu
  image_build:
    type: image_build:v3.0
    param:
      workspace: jianmu-runner-qiniu
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      docker_file: Dockerfile
      image_name: jianmudev/jianmu-runner-qiniu
      image_tag: 0.1.1
      docker_build_path: .