param:
  image_name: jianmudev/jianmu-runner-qiniu

pipeline:
  name: 构建七牛云节点定义docker镜像
  ref: jianmu_runner_qiniu_image_builder
  description: 构建七牛云节点定义docker镜像
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-runners/jianmu-runner-qiniu.git
      ref: refs/heads/master
  node_build:
    type: nodejs_build:1.0.0-14.16.1
    param:
      workspace: ${git_clone.git_path}
  image_build:
    type: docker_image_build:1.0.0
    param:
      workspace: ${git_clone.git_path}
      docker_username: ((dockerhub.username))
      docker_password: ((dockerhub.password))
      docker_file: Dockerfile
      image_name: ${global.image_name}
      image_tag: ${node_build.package_version}
      docker_build_path: .
  send_message:
    type: qywx_notice:1.0.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "七牛云节点定义docker镜像构建完成。\n镜像${global.image_name}:${node_build.package_version}"
      msgtype: "text"
      mentioned_list: "[]"