pipeline:
  name: 发布七牛云节点定义
  ref: jianmu_runner_qiniu_publisher
  description: 发布七牛云节点定义
  git_clone:
    type: git_clone:1.0.0
    param:
      remote_url: https://gitee.com/jianmu-runners/jianmu-runner-qiniu.git
      ref: refs/heads/master
  hub_publish:
    type: hub_publish:1.0.0
    param:
      hub_url: https://hub.jianmu.run
      dsl_file_path:  ${git_clone.git_path}/dsl/node_def.yml
      hub_appkey: ((jianmuhub.appkey))